-- ============================================================================
-- Medico-Legal Case Management System
-- PostgreSQL relational schema
-- Based on the approved final ER diagram
--
-- Run this file while connected to the database:
--     medico_legal_case_management
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 0. SHARED FUNCTION FOR AUTOMATIC UPDATED_AT VALUES
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- 1. ORGANISATIONAL, STAFF, USER, AND ROLE TABLES
-- ---------------------------------------------------------------------------

CREATE TABLE hospital (
    hospital_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_name varchar(200) NOT NULL,
    district varchar(100) NOT NULL,
    address varchar(500)
);

CREATE TABLE jmo_office (
    jmo_office_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_name varchar(200) NOT NULL,
    hospital_id integer NOT NULL,
    district varchar(100) NOT NULL,
    contact_no varchar(30),
    CONSTRAINT fk_jmo_office_hospital
        FOREIGN KEY (hospital_id) REFERENCES hospital(hospital_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE ward (
    ward_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id integer NOT NULL,
    ward_name varchar(120) NOT NULL,
    ward_type varchar(100),
    CONSTRAINT uq_ward_hospital_name UNIQUE (hospital_id, ward_name),
    CONSTRAINT fk_ward_hospital
        FOREIGN KEY (hospital_id) REFERENCES hospital(hospital_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE doctor (
    doctor_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(200) NOT NULL,
    designation varchar(150) NOT NULL,
    slmc_reg_no varchar(50),
    contact_no varchar(30),
    current_office_id integer,
    employment_status varchar(50) NOT NULL DEFAULT 'Active',
    CONSTRAINT uq_doctor_slmc_reg_no UNIQUE (slmc_reg_no),
    CONSTRAINT fk_doctor_current_office
        FOREIGN KEY (current_office_id) REFERENCES jmo_office(jmo_office_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE roles (
    role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name varchar(100) NOT NULL,
    description varchar(500),
    CONSTRAINT uq_role_name UNIQUE (role_name)
);

CREATE TABLE user_account (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id uuid,
    username varchar(100) NOT NULL,
    password_hash varchar(255),
    full_name varchar(200) NOT NULL,
    email varchar(255),
    contact_no varchar(30),
    account_status varchar(50) NOT NULL DEFAULT 'Active',
    doctor_id integer,
    jmo_office_id integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login timestamptz,
    CONSTRAINT uq_user_account_username UNIQUE (username),
    CONSTRAINT uq_user_account_email UNIQUE (email),
    CONSTRAINT uq_user_account_auth_user_id UNIQUE (auth_user_id),
    CONSTRAINT fk_user_account_auth_user
        FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_user_account_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctor(doctor_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_user_account_jmo_office
        FOREIGN KEY (jmo_office_id) REFERENCES jmo_office(jmo_office_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE user_role (
    user_role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id) REFERENCES roles(role_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE staff_posting (
    posting_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    jmo_office_id integer NOT NULL,
    start_date date NOT NULL,
    end_date date,
    posting_status varchar(50) NOT NULL DEFAULT 'Active',
    CONSTRAINT chk_staff_posting_dates
        CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT fk_staff_posting_user
        FOREIGN KEY (user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_staff_posting_jmo_office
        FOREIGN KEY (jmo_office_id) REFERENCES jmo_office(jmo_office_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ---------------------------------------------------------------------------
-- 2. EXTERNAL ORGANISATIONS: POLICE, COURT, MAGISTRATE / ISD
-- ---------------------------------------------------------------------------

CREATE TABLE police_station (
    police_station_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_name varchar(200) NOT NULL,
    division varchar(150),
    district varchar(100) NOT NULL,
    contact_no varchar(30),
    CONSTRAINT uq_police_station_name_district UNIQUE (station_name, district)
);

CREATE TABLE police_officer (
    police_officer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    officer_name varchar(200) NOT NULL,
    rank varchar(100),
    badge_no varchar(80),
    contact_no varchar(30),
    police_station_id integer NOT NULL,
    CONSTRAINT uq_police_officer_badge_no UNIQUE (badge_no),
    CONSTRAINT fk_police_officer_station
        FOREIGN KEY (police_station_id) REFERENCES police_station(police_station_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE court (
    court_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    court_name varchar(200) NOT NULL,
    district varchar(100) NOT NULL,
    address varchar(500),
    CONSTRAINT uq_court_name_district UNIQUE (court_name, district)
);

CREATE TABLE magistrate_isd (
    magistrate_isd_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(200) NOT NULL,
    designation varchar(150) NOT NULL,
    area_of_authority varchar(200),
    contact_no varchar(30)
);

-- ---------------------------------------------------------------------------
-- 3. PATIENT / VICTIM / DECEASED PERSON TABLES
-- ---------------------------------------------------------------------------

CREATE TABLE patient_victim (
    patient_id varchar(30) PRIMARY KEY,
    full_name varchar(200) NOT NULL,
    nic_passport_no varchar(80),
    date_of_birth date,
    age smallint,
    gender varchar(30),
    permanent_address varchar(500),
    contact_no varchar(30),
    hospital_no varchar(100),
    bht_no varchar(100),
    nationality varchar(100),
    ethnicity varchar(100),
    person_status varchar(50) NOT NULL,
    is_minor boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_patient_victim_nic_passport_no UNIQUE (nic_passport_no),
    CONSTRAINT chk_patient_age CHECK (age IS NULL OR age BETWEEN 0 AND 150),
    CONSTRAINT chk_patient_person_status
        CHECK (person_status IN ('Living', 'Deceased', 'Unknown'))
);

CREATE TRIGGER trg_patient_victim_set_updated_at
BEFORE UPDATE ON patient_victim
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE living_patient_details (
    patient_id varchar(30) PRIMARY KEY,
    current_condition varchar(255),
    consent_status varchar(100),
    guardian_name varchar(200),
    guardian_contact varchar(30),
    CONSTRAINT fk_living_patient_details_patient
        FOREIGN KEY (patient_id) REFERENCES patient_victim(patient_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE deceased_person_details (
    patient_id varchar(30) PRIMARY KEY,
    date_of_death date,
    time_of_death time,
    place_of_death varchar(500),
    occupation varchar(150),
    identification_status varchar(100),
    body_received_datetime timestamptz,
    CONSTRAINT fk_deceased_person_details_patient
        FOREIGN KEY (patient_id) REFERENCES patient_victim(patient_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE next_of_kin (
    next_of_kin_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id varchar(30) NOT NULL,
    full_name varchar(200) NOT NULL,
    relationship varchar(100) NOT NULL,
    contact_no varchar(30),
    address varchar(500),
    CONSTRAINT fk_next_of_kin_patient
        FOREIGN KEY (patient_id) REFERENCES patient_victim(patient_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- 4. CASE REGISTRATION AND CASE SPECIALISATION TABLES
-- ---------------------------------------------------------------------------

CREATE TABLE forensic_case (
    case_id varchar(30) PRIMARY KEY,
    case_type varchar(50) NOT NULL,
    case_category varchar(100),
    case_status varchar(100) NOT NULL DEFAULT 'Registered',
    registered_datetime timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    patient_id varchar(30) NOT NULL,
    registered_by_user_id integer NOT NULL,
    jmo_office_id integer NOT NULL,
    confidentiality_level varchar(50) NOT NULL DEFAULT 'Standard',
    is_sexual_assault_case boolean NOT NULL DEFAULT false,
    CONSTRAINT chk_forensic_case_type
        CHECK (case_type IN ('Clinical', 'Autopsy')),
    CONSTRAINT fk_forensic_case_patient
        FOREIGN KEY (patient_id) REFERENCES patient_victim(patient_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_forensic_case_registered_by
        FOREIGN KEY (registered_by_user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_forensic_case_jmo_office
        FOREIGN KEY (jmo_office_id) REFERENCES jmo_office(jmo_office_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE clinical_case_details (
    case_id varchar(30) PRIMARY KEY,
    mlef_no varchar(100),
    mlef_issued_date date,
    reason_for_examination varchar(500),
    patient_history text,
    alcohol_consumption_status varchar(100),
    drug_consumption_status varchar(100),
    nature_of_harm varchar(300),
    nature_of_weapon varchar(300),
    hurt_category varchar(100),
    mlr_serial_no varchar(100),
    CONSTRAINT uq_clinical_case_mlef_no UNIQUE (mlef_no),
    CONSTRAINT fk_clinical_case_details_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE autopsy_case_details (
    case_id varchar(30) PRIMARY KEY,
    pm_registry_no varchar(100),
    inquest_no varchar(100),
    court_order_no varchar(100),
    death_report_no varchar(100),
    date_of_inquest date,
    place_of_pm varchar(300),
    cause_of_death_summary text,
    manner_of_death varchar(100),
    CONSTRAINT uq_autopsy_case_pm_registry_no UNIQUE (pm_registry_no),
    CONSTRAINT fk_autopsy_case_details_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE hospital_admission (
    admission_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id varchar(30) NOT NULL,
    hospital_id integer NOT NULL,
    ward_id integer,
    bed_no varchar(50),
    admitted_datetime timestamptz,
    discharged_datetime timestamptz,
    CONSTRAINT chk_hospital_admission_dates
        CHECK (
            discharged_datetime IS NULL
            OR admitted_datetime IS NULL
            OR discharged_datetime >= admitted_datetime
        ),
    CONSTRAINT fk_hospital_admission_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_hospital_admission_hospital
        FOREIGN KEY (hospital_id) REFERENCES hospital(hospital_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_hospital_admission_ward
        FOREIGN KEY (ward_id) REFERENCES ward(ward_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE case_doctor (
    case_doctor_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id varchar(30) NOT NULL,
    doctor_id integer NOT NULL,
    role_in_case varchar(100) NOT NULL,
    assigned_date date NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    status varchar(50) NOT NULL DEFAULT 'Assigned',
    CONSTRAINT uq_case_doctor_role UNIQUE (case_id, doctor_id, role_in_case),
    CONSTRAINT fk_case_doctor_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_case_doctor_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctor(doctor_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ---------------------------------------------------------------------------
-- 5. EXAMINATIONS, FINDINGS, INJURIES, SAMPLES, AND LABORATORY TABLES
-- ---------------------------------------------------------------------------

CREATE TABLE examination (
    examination_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id varchar(30) NOT NULL,
    exam_type varchar(100) NOT NULL,
    exam_datetime timestamptz NOT NULL,
    exam_place varchar(300),
    examination_status varchar(100) NOT NULL DEFAULT 'Scheduled',
    notes text,
    created_by_user_id integer NOT NULL,
    CONSTRAINT fk_examination_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_examination_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE examination_doctor (
    examination_doctor_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    examination_id integer NOT NULL,
    doctor_id integer NOT NULL,
    role_in_examination varchar(100) NOT NULL,
    CONSTRAINT uq_examination_doctor_role
        UNIQUE (examination_id, doctor_id, role_in_examination),
    CONSTRAINT fk_examination_doctor_examination
        FOREIGN KEY (examination_id) REFERENCES examination(examination_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_examination_doctor_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctor(doctor_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE injury (
    injury_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    examination_id integer NOT NULL,
    injury_type varchar(100) NOT NULL,
    body_location varchar(200) NOT NULL,
    side varchar(30),
    length numeric(8,2),
    width numeric(8,2),
    depth numeric(8,2),
    description text,
    injury_age varchar(100),
    severity varchar(100),
    weapon_opinion varchar(300),
    is_fatal boolean NOT NULL DEFAULT false,
    CONSTRAINT chk_injury_dimensions
        CHECK (
            (length IS NULL OR length >= 0)
            AND (width IS NULL OR width >= 0)
            AND (depth IS NULL OR depth >= 0)
        ),
    CONSTRAINT fk_injury_examination
        FOREIGN KEY (examination_id) REFERENCES examination(examination_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE internal_finding (
    internal_finding_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    examination_id integer NOT NULL,
    organ_name varchar(150) NOT NULL,
    finding_description text NOT NULL,
    pathological_condition varchar(500),
    CONSTRAINT fk_internal_finding_examination
        FOREIGN KEY (examination_id) REFERENCES examination(examination_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE body_diagram_marking (
    marking_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    examination_id integer NOT NULL,
    injury_id integer,
    body_region varchar(200) NOT NULL,
    x_coordinate numeric(9,3),
    y_coordinate numeric(9,3),
    marking_description text,
    CONSTRAINT fk_body_diagram_marking_examination
        FOREIGN KEY (examination_id) REFERENCES examination(examination_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_body_diagram_marking_injury
        FOREIGN KEY (injury_id) REFERENCES injury(injury_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE sample_evidence (
    sample_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_reference varchar(50) UNIQUE,
    case_id varchar(30) NOT NULL,
    examination_id integer,
    sample_type varchar(150) NOT NULL,
    collected_datetime timestamptz NOT NULL,
    collected_by_doctor_id integer,
    seal_no varchar(100),
    storage_condition varchar(200),
    sample_status varchar(100) NOT NULL DEFAULT 'Collected',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_sample_evidence_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sample_evidence_examination
        FOREIGN KEY (examination_id) REFERENCES examination(examination_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_sample_evidence_collected_by
        FOREIGN KEY (collected_by_doctor_id) REFERENCES doctor(doctor_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE laboratory (
    laboratory_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratory_name varchar(200) NOT NULL,
    location varchar(300),
    contact_no varchar(30)
);

CREATE TABLE lab_request (
    lab_request_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_reference varchar(50) UNIQUE,
    sample_id integer NOT NULL,
    laboratory_id integer NOT NULL,
    requested_test_type varchar(150) NOT NULL,
    requested_date date NOT NULL,
    requested_by_doctor_id integer,
    request_status varchar(100) NOT NULL DEFAULT 'Requested',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_lab_request_sample
        FOREIGN KEY (sample_id) REFERENCES sample_evidence(sample_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_lab_request_laboratory
        FOREIGN KEY (laboratory_id) REFERENCES laboratory(laboratory_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_lab_request_requested_by
        FOREIGN KEY (requested_by_doctor_id) REFERENCES doctor(doctor_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

-- ---------------------------------------------------------------------------
-- 6. REPORTS, DOCUMENTS, REFERRALS, COURT CASES, AND CUSTODY
-- ---------------------------------------------------------------------------

CREATE TABLE report (
    report_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id varchar(30) NOT NULL,
    report_type varchar(100) NOT NULL,
    current_status varchar(100) NOT NULL DEFAULT 'Draft',
    created_by_user_id integer NOT NULL,
    generated_date date,
    submitted_date date,
    CONSTRAINT fk_report_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_report_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE case_document (
    document_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id varchar(30) NOT NULL,
    examination_id integer,
    report_id integer,
    sample_id integer,
    document_type varchar(150) NOT NULL,
    file_name varchar(500) NOT NULL,
    file_format varchar(30) NOT NULL,
    file_size bigint,
    storage_location varchar(1000) NOT NULL,
    uploaded_datetime timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    uploaded_by_user_id integer NOT NULL,
    version_no integer NOT NULL DEFAULT 1,
    is_active boolean NOT NULL DEFAULT true,
    access_level varchar(100) NOT NULL DEFAULT 'Standard',
    checksum char(64),
    CONSTRAINT chk_case_document_file_size CHECK (file_size IS NULL OR file_size >= 0),
    CONSTRAINT chk_case_document_version CHECK (version_no >= 1),
    CONSTRAINT fk_case_document_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_case_document_examination
        FOREIGN KEY (examination_id) REFERENCES examination(examination_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_case_document_report
        FOREIGN KEY (report_id) REFERENCES report(report_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_case_document_sample
        FOREIGN KEY (sample_id) REFERENCES sample_evidence(sample_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_case_document_uploaded_by
        FOREIGN KEY (uploaded_by_user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE case_referral (
    referral_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id varchar(30) NOT NULL,
    referral_type varchar(100) NOT NULL,
    reference_no varchar(150),
    issued_date date,
    reason varchar(500),
    police_officer_id integer,
    police_station_id integer,
    court_id integer,
    magistrate_isd_id integer,
    referral_document_id integer,
    CONSTRAINT fk_case_referral_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_case_referral_police_officer
        FOREIGN KEY (police_officer_id) REFERENCES police_officer(police_officer_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_case_referral_police_station
        FOREIGN KEY (police_station_id) REFERENCES police_station(police_station_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_case_referral_court
        FOREIGN KEY (court_id) REFERENCES court(court_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_case_referral_magistrate_isd
        FOREIGN KEY (magistrate_isd_id) REFERENCES magistrate_isd(magistrate_isd_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_case_referral_document
        FOREIGN KEY (referral_document_id) REFERENCES case_document(document_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE court_case (
    court_case_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id varchar(30) NOT NULL,
    court_id integer NOT NULL,
    court_reference_no varchar(150) NOT NULL,
    trial_date date,
    case_status_in_court varchar(100),
    CONSTRAINT uq_court_case_reference UNIQUE (court_id, court_reference_no),
    CONSTRAINT fk_court_case_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_court_case_court
        FOREIGN KEY (court_id) REFERENCES court(court_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE authority_coordination_record (
    coordination_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_type varchar(30) NOT NULL,
    case_id varchar(30) NOT NULL,
    reference_no varchar(150) NOT NULL UNIQUE,
    authority_name varchar(200) NOT NULL,
    contact_person varchar(200),
    action_date date,
    coordination_status varchar(30) NOT NULL DEFAULT 'Pending',
    priority varchar(30) NOT NULL DEFAULT 'Normal',
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_coordination_record_type
        CHECK (record_type IN ('Police Referral', 'Court Matter')),
    CONSTRAINT chk_coordination_status
        CHECK (coordination_status IN ('Pending', 'Scheduled', 'Submitted', 'Completed')),
    CONSTRAINT chk_coordination_priority
        CHECK (priority IN ('Normal', 'Urgent', 'Court Priority')),
    CONSTRAINT fk_coordination_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE lab_result (
    lab_result_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_request_id integer NOT NULL,
    result_summary text,
    result_details text,
    result_date date,
    entered_by_user_id integer,
    result_document_id integer,
    CONSTRAINT fk_lab_result_request
        FOREIGN KEY (lab_request_id) REFERENCES lab_request(lab_request_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_lab_result_entered_by
        FOREIGN KEY (entered_by_user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_lab_result_document
        FOREIGN KEY (result_document_id) REFERENCES case_document(document_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE chain_of_custody (
    custody_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id integer NOT NULL,
    from_user_id integer,
    to_user_id integer,
    transfer_datetime timestamptz NOT NULL,
    action_type varchar(100) NOT NULL,
    seal_status varchar(100),
    remarks text,
    CONSTRAINT fk_chain_of_custody_sample
        FOREIGN KEY (sample_id) REFERENCES sample_evidence(sample_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_chain_of_custody_from_user
        FOREIGN KEY (from_user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_chain_of_custody_to_user
        FOREIGN KEY (to_user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE report_version (
    report_version_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id integer NOT NULL,
    version_no integer NOT NULL,
    status varchar(100) NOT NULL DEFAULT 'Draft',
    report_document_id integer,
    created_datetime timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id integer NOT NULL,
    approved_by_doctor_id integer,
    approved_datetime timestamptz,
    CONSTRAINT uq_report_version UNIQUE (report_id, version_no),
    CONSTRAINT chk_report_version_number CHECK (version_no >= 1),
    CONSTRAINT fk_report_version_report
        FOREIGN KEY (report_id) REFERENCES report(report_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_report_version_document
        FOREIGN KEY (report_document_id) REFERENCES case_document(document_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_report_version_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_report_version_approved_by
        FOREIGN KEY (approved_by_doctor_id) REFERENCES doctor(doctor_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE report_signatory (
    report_signatory_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_version_id integer NOT NULL,
    doctor_id integer NOT NULL,
    signatory_role varchar(100) NOT NULL,
    signed_datetime timestamptz,
    signature_status varchar(100) NOT NULL DEFAULT 'Pending',
    CONSTRAINT uq_report_signatory
        UNIQUE (report_version_id, doctor_id, signatory_role),
    CONSTRAINT fk_report_signatory_report_version
        FOREIGN KEY (report_version_id) REFERENCES report_version(report_version_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_report_signatory_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctor(doctor_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE report_dispatch (
    dispatch_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id integer NOT NULL,
    recipient_type varchar(50) NOT NULL,
    court_id integer,
    police_station_id integer,
    dispatch_date date NOT NULL,
    delivery_method varchar(100) NOT NULL,
    receipt_no varchar(150),
    receipt_date date,
    received_by varchar(200),
    receipt_document_id integer,
    CONSTRAINT chk_report_dispatch_recipient
        CHECK (court_id IS NOT NULL OR police_station_id IS NOT NULL),
    CONSTRAINT fk_report_dispatch_report
        FOREIGN KEY (report_id) REFERENCES report(report_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_report_dispatch_court
        FOREIGN KEY (court_id) REFERENCES court(court_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_report_dispatch_police_station
        FOREIGN KEY (police_station_id) REFERENCES police_station(police_station_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_report_dispatch_receipt_document
        FOREIGN KEY (receipt_document_id) REFERENCES case_document(document_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

-- ---------------------------------------------------------------------------
-- 7. TASKS, NOTIFICATIONS, AND AUDIT LOGS
-- ---------------------------------------------------------------------------

CREATE TABLE task_notification (
    task_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id varchar(30) NOT NULL,
    assigned_to_user_id integer NOT NULL,
    task_type varchar(150) NOT NULL,
    due_date date,
    status varchar(100) NOT NULL DEFAULT 'Open',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamptz,
    CONSTRAINT fk_task_notification_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_task_notification_assigned_to
        FOREIGN KEY (assigned_to_user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE audit_log (
    audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    action varchar(100) NOT NULL,
    table_name varchar(100) NOT NULL,
    record_id varchar(100) NOT NULL,
    old_value text,
    new_value text,
    action_datetime timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address inet,
    CONSTRAINT fk_audit_log_user
        FOREIGN KEY (user_id) REFERENCES user_account(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

-- ---------------------------------------------------------------------------
-- 8. PERFORMANCE INDEXES FOR SEARCH AND DASHBOARD QUERIES
-- ---------------------------------------------------------------------------

CREATE INDEX idx_patient_victim_name ON patient_victim(full_name);
CREATE INDEX idx_patient_victim_hospital_no ON patient_victim(hospital_no);
CREATE INDEX idx_patient_victim_bht_no ON patient_victim(bht_no);

CREATE INDEX idx_forensic_case_patient ON forensic_case(patient_id);
CREATE INDEX idx_forensic_case_office_status ON forensic_case(jmo_office_id, case_status);
CREATE INDEX idx_forensic_case_type_status ON forensic_case(case_type, case_status);
CREATE INDEX idx_forensic_case_registered_datetime ON forensic_case(registered_datetime);

CREATE INDEX idx_examination_case_datetime ON examination(case_id, exam_datetime);
CREATE INDEX idx_sample_evidence_case_status ON sample_evidence(case_id, sample_status);
CREATE INDEX idx_lab_request_status ON lab_request(request_status);
CREATE INDEX idx_report_case_status ON report(case_id, current_status);
CREATE INDEX idx_case_document_case_type ON case_document(case_id, document_type);
CREATE INDEX idx_court_case_trial_date ON court_case(trial_date);
CREATE INDEX idx_coordination_case ON authority_coordination_record(case_id);
CREATE INDEX idx_coordination_action_status
    ON authority_coordination_record(action_date, coordination_status);
CREATE INDEX idx_task_notification_assignee_status_due
    ON task_notification(assigned_to_user_id, status, due_date);
CREATE INDEX idx_audit_log_user_datetime ON audit_log(user_id, action_datetime);

-- Only one doctor may be marked as the primary doctor for one case.
CREATE UNIQUE INDEX uq_case_doctor_one_primary
    ON case_doctor(case_id)
    WHERE is_primary;

-- ---------------------------------------------------------------------------
-- 9. INITIAL USER ROLES
-- ---------------------------------------------------------------------------

INSERT INTO roles (role_name, description) VALUES
    ('System Administrator', 'Full system configuration, user management, and audit access'),
    ('Consultant JMO', 'Full case access, report approval, and report sign-off'),
    ('Medical Officer Medico-Legal', 'Case and examination data entry; draft report creation'),
    ('Assistant JMO', 'Assigned-case viewing and partial examination data entry'),
    ('Administrative Clerk', 'Case registration, report printing, correspondence, and document upload'),
    ('Laboratory Staff', 'Laboratory result entry for linked cases'),
    ('Police Liaison', 'Limited view-only access to own submitted case reports'),
    ('Read-Only User', 'Read-only access to approved records permitted by role')
ON CONFLICT (role_name) DO NOTHING;

COMMIT;

-- Verification queries (run after the transaction completes):
-- SELECT table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'public'
-- ORDER BY table_name;
--
-- SELECT role_id, role_name FROM roles ORDER BY role_id;
